// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: airfone/api.proto

package airfone

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AirfoneClient is the client API for Airfone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AirfoneClient interface {
}

type airfoneClient struct {
	cc grpc.ClientConnInterface
}

func NewAirfoneClient(cc grpc.ClientConnInterface) AirfoneClient {
	return &airfoneClient{cc}
}

// AirfoneServer is the server API for Airfone service.
// All implementations must embed UnimplementedAirfoneServer
// for forward compatibility
type AirfoneServer interface {
	mustEmbedUnimplementedAirfoneServer()
}

// UnimplementedAirfoneServer must be embedded to have forward compatible implementations.
type UnimplementedAirfoneServer struct {
}

func (UnimplementedAirfoneServer) mustEmbedUnimplementedAirfoneServer() {}

// UnsafeAirfoneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AirfoneServer will
// result in compilation errors.
type UnsafeAirfoneServer interface {
	mustEmbedUnimplementedAirfoneServer()
}

func RegisterAirfoneServer(s grpc.ServiceRegistrar, srv AirfoneServer) {
	s.RegisterService(&Airfone_ServiceDesc, srv)
}

// Airfone_ServiceDesc is the grpc.ServiceDesc for Airfone service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Airfone_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.airfone.Airfone",
	HandlerType: (*AirfoneServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "airfone/api.proto",
}
