// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: airfone/keepalive.proto

package airfone

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 心跳返回信号
type TickerType int32

const (
	TickerType_OK      TickerType = 0 // 一切正常
	TickerType_CHANGED TickerType = 1 // 部分依赖内容已改变，需要重新拉取
	TickerType_ERROR   TickerType = 2 // 上游服务已崩坏，依赖服务不可用
)

// Enum value maps for TickerType.
var (
	TickerType_name = map[int32]string{
		0: "OK",
		1: "CHANGED",
		2: "ERROR",
	}
	TickerType_value = map[string]int32{
		"OK":      0,
		"CHANGED": 1,
		"ERROR":   2,
	}
)

func (x TickerType) Enum() *TickerType {
	p := new(TickerType)
	*p = x
	return p
}

func (x TickerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TickerType) Descriptor() protoreflect.EnumDescriptor {
	return file_airfone_keepalive_proto_enumTypes[0].Descriptor()
}

func (TickerType) Type() protoreflect.EnumType {
	return &file_airfone_keepalive_proto_enumTypes[0]
}

func (x TickerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TickerType.Descriptor instead.
func (TickerType) EnumDescriptor() ([]byte, []int) {
	return file_airfone_keepalive_proto_rawDescGZIP(), []int{0}
}

// 心跳
type Keepalive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type TickerType `protobuf:"varint,1,opt,name=type,proto3,enum=api.airfone.TickerType" json:"type,omitempty"`
}

func (x *Keepalive) Reset() {
	*x = Keepalive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_airfone_keepalive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Keepalive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keepalive) ProtoMessage() {}

func (x *Keepalive) ProtoReflect() protoreflect.Message {
	mi := &file_airfone_keepalive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keepalive.ProtoReflect.Descriptor instead.
func (*Keepalive) Descriptor() ([]byte, []int) {
	return file_airfone_keepalive_proto_rawDescGZIP(), []int{0}
}

func (x *Keepalive) GetType() TickerType {
	if x != nil {
		return x.Type
	}
	return TickerType_OK
}

type KeepaliveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KeepaliveRequest) Reset() {
	*x = KeepaliveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_airfone_keepalive_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepaliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepaliveRequest) ProtoMessage() {}

func (x *KeepaliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_airfone_keepalive_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepaliveRequest.ProtoReflect.Descriptor instead.
func (*KeepaliveRequest) Descriptor() ([]byte, []int) {
	return file_airfone_keepalive_proto_rawDescGZIP(), []int{1}
}

type KeepaliveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status TickerType `protobuf:"varint,1,opt,name=status,proto3,enum=api.airfone.TickerType" json:"status,omitempty"`
}

func (x *KeepaliveResponse) Reset() {
	*x = KeepaliveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_airfone_keepalive_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepaliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepaliveResponse) ProtoMessage() {}

func (x *KeepaliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_airfone_keepalive_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepaliveResponse.ProtoReflect.Descriptor instead.
func (*KeepaliveResponse) Descriptor() ([]byte, []int) {
	return file_airfone_keepalive_proto_rawDescGZIP(), []int{2}
}

func (x *KeepaliveResponse) GetStatus() TickerType {
	if x != nil {
		return x.Status
	}
	return TickerType_OK
}

var File_airfone_keepalive_proto protoreflect.FileDescriptor

var file_airfone_keepalive_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x69, 0x72, 0x66, 0x6f, 0x6e, 0x65, 0x2f, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c,
	0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x69, 0x72, 0x66, 0x6f, 0x6e, 0x65, 0x22, 0x38, 0x0a, 0x09, 0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c,
	0x69, 0x76, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x69, 0x72, 0x66, 0x6f, 0x6e, 0x65, 0x2e,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x12, 0x0a, 0x10, 0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x44, 0x0a, 0x11, 0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x69, 0x72, 0x66, 0x6f, 0x6e, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x2c, 0x0a, 0x0a, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x44, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x42, 0x2c, 0x0a, 0x0b, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x69, 0x72, 0x66, 0x6f, 0x6e, 0x65, 0x50, 0x01, 0x5a, 0x1b, 0x41, 0x69, 0x72, 0x66, 0x6f,
	0x6e, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x69, 0x72, 0x66, 0x6f, 0x6e, 0x65, 0x3b, 0x61,
	0x69, 0x72, 0x66, 0x6f, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_airfone_keepalive_proto_rawDescOnce sync.Once
	file_airfone_keepalive_proto_rawDescData = file_airfone_keepalive_proto_rawDesc
)

func file_airfone_keepalive_proto_rawDescGZIP() []byte {
	file_airfone_keepalive_proto_rawDescOnce.Do(func() {
		file_airfone_keepalive_proto_rawDescData = protoimpl.X.CompressGZIP(file_airfone_keepalive_proto_rawDescData)
	})
	return file_airfone_keepalive_proto_rawDescData
}

var file_airfone_keepalive_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_airfone_keepalive_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_airfone_keepalive_proto_goTypes = []interface{}{
	(TickerType)(0),           // 0: api.airfone.TickerType
	(*Keepalive)(nil),         // 1: api.airfone.Keepalive
	(*KeepaliveRequest)(nil),  // 2: api.airfone.KeepaliveRequest
	(*KeepaliveResponse)(nil), // 3: api.airfone.KeepaliveResponse
}
var file_airfone_keepalive_proto_depIdxs = []int32{
	0, // 0: api.airfone.Keepalive.type:type_name -> api.airfone.TickerType
	0, // 1: api.airfone.KeepaliveResponse.status:type_name -> api.airfone.TickerType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_airfone_keepalive_proto_init() }
func file_airfone_keepalive_proto_init() {
	if File_airfone_keepalive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_airfone_keepalive_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Keepalive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_airfone_keepalive_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepaliveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_airfone_keepalive_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepaliveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_airfone_keepalive_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_airfone_keepalive_proto_goTypes,
		DependencyIndexes: file_airfone_keepalive_proto_depIdxs,
		EnumInfos:         file_airfone_keepalive_proto_enumTypes,
		MessageInfos:      file_airfone_keepalive_proto_msgTypes,
	}.Build()
	File_airfone_keepalive_proto = out.File
	file_airfone_keepalive_proto_rawDesc = nil
	file_airfone_keepalive_proto_goTypes = nil
	file_airfone_keepalive_proto_depIdxs = nil
}
